### ISSUE TITLE
OpenWeatherMap key didn't migrate correctly after updating from v135 to v136

### ISSUE THREAD

**Issue by grizzlysmit** [penguin-teal/gnome-openweather#40]
## Description

I upgraded to version 136 and now it won't work with my apikey for openweatherMap

## System

Which Linux distro are you using?  Ubuntu 24.04

## Settings

```json
{"app-version":"136","git-version":"136.r1.g8d02397","gnome-version":"46.0","user-locale":"en","appid":"<KEY>","weather-provider":"'openweathermap'","has-run":"true","locs":"[(0, '<NAME>', 0, '<PLACE>')]","owm-api-translate":"false","show-sunsetrise-in-panel":"false","last-init-error":"'(2024/05/11) TypeError: settings.set_value is not a function'","my-loc-prov":"'ipinfoio'","weatherapidotcom-key":"<KEY>","position-index":"6","geolocation-provider":"'mapquest'","use-default-weatherapidotcom-key":"true","geolocation-appid-mapquest":"'*************************'","clock-format":"'24h'","position-in-panel":"'left'","show-comment-in-panel":"false"}
```

I starred out the location api key for security it didn't even take the weather api key

**Comment by penguin-teal** [comment]
A new format was made for the weather keys and it was supposed to automatically migrate these but for some reason it seems to have failed. If you re-enter your key like you did before you should be up and running but I will leave this open and investigate why it didn't migrate correctly. Thanks for the report!

**Comment by penguin-teal** [comment]
Also your geolocation mapquest key should have been redacted I will also fix that.

**Comment by robatino** [comment]
> A new format was made for the weather keys and it was supposed to automatically migrate these but for some reason it seems to have failed. If you re-enter your key like you did before you should be up and running but I will leave this open and investigate why it didn't migrate correctly. Thanks for the report!

The new version at first appears to allow me to enter my personal API settings for each provider. However, if I switch to a different provider and then switch back, the settings I just entered for the first provider are no longer visible. ("Use Custom API Key" is set back to off, and the "Personal API Key" box is blank.) I can't tell if the settings were actually stored or not.

**Comment by derek-shnosh** [comment]
I am experiencing similar behavior, after the upgrade my settings are not saving the "Use Custom API Key" toggle state, or the "Personal API Key" value. I have tried using the Restore Defaults option and reconfiguring, but the behavior is the same.

https://github.com/penguin-teal/gnome-openweather/assets/21090563/516598b9-94e5-4de5-ad9f-2c1976f679d7

**Comment by penguin-teal** [comment]
MapQuest key not redacted: d039a90fbff54c152598288ba3dec785f8282481
Settings for keys glitching: 0648ad8cd0010f346aada9bc75857c6dd7cf8669

The bug had to do with the GUI widgets. I am still trying to figure out why the keys didn't migrate.

**Comment by grizzlysmit** [comment]
umm I still can't get an update so for me it's not fixed

**Comment by penguin-teal** [comment]
It's been fixed in the development version however I haven't made a release yet. I will make a release soon once I've done some stuff and ensured it is stable to prevent a large bug like this to release again.
